Practice/4_Django/221020/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<int:user_pk>/', views.detail, name='detail'),

    path('profile/', views.profile, name='profile'),   # 프로필 작성 페이지
]

Practice/4_Django/221020/articles/urls.py
from django.urls import path
from . import views


app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:article_pk>/', views.detail, name='detail'),
    path('<int:article_pk>/update/', views.update, name='update'),
    path('<int:article_pk>/delete/', views.delete, name='delete'),
    path('<int:article_pk>/comments/', views.create_comment, name='create_comment'),    # 댓글 생성
    path('<int:article_pk>/comments/<int:comment_pk>/delete/', views.delete_comment, name='delete_comment'),    # 댓글 삭제
]

Practice/4_Django/221020/pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('articles/', include('articles.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Practice/4_Django/221020/templates/base.html
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <style>
      .card:hover {
        transform: scale(1.05);
        box-shadow: 0 10px 20px rgba(0,0,0,.12), 0 4px 8px rgba(0,0,0,.06);
        transition: transform 0.3s;
      }
      
      .card-body-text {
        display: -webkit-box;
        min-height: 72px;
        line-height: 24px;  /* line-height * line-clapm */
        overflow: hidden;
        text-overflow: ellipsis;
        word-wrap: break-word;
        -webkit-line-clamp: 3;
        -webkit-box-orient: vertical;
      }
    </style>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'articles:index' %}">HOME</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              {% if request.resolver_match.url_name == 'index' %}
                <a class="nav-link active" href="{% url 'articles:index' %}">HOME</a>
              {% else %}
                <a class="nav-link" href="{% url 'articles:index' %}">HOME</a>
              {% endif %}
            </li>

            <!-- 로그인 O -->
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                {% if request.resolver_match.url_name == 'create' %}
                  <a class="nav-link active" href="{% url 'articles:create' %}">Write</a>
                {% else %}
                  <a class="nav-link" href="{% url 'articles:create' %}">Write</a>
                {% endif %}
              </li>

              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:detail' request.user.pk %}">{{ request.user.username }}'s Page</a>
              </li>

              <li class="nav-item">
                <form action="{% url 'accounts:logout' %}" method="POST" class="m-0">
                  {% csrf_token %}
                  <input type="submit" class="nav-link" style="background: none; border: none;" value="Logout">
                </form>
              </li>
            <!-- 로그인 X -->
            {% else %}
              <li class="nav-item">
                <form action="{% url 'accounts:signup' %}" method="GET" class="m-0">
                  {% csrf_token %}
                  {% if request.resolver_match.url_name == 'signup' %}
                    <input type="submit" class="nav-link active" style="background: none; border: none;" value="Signup">
                  {% else %}
                    <input type="submit" class="nav-link" style="background: none; border: none;" value="Signup">
                  {% endif %}
                </form>
              </li>
              <li class="nav-item">
                <form action="{% url 'accounts:login' %}" method="GET" class="m-0">
                  {% csrf_token %}
                  {% if request.resolver_match.url_name == 'login' %}
                    <input type="submit" class="nav-link active" style="background: none; border: none;" value="Login">
                  {% else %}
                    <input type="submit" class="nav-link" style="background: none; border: none;" value="Login">
                  {% endif %}
                </form>
              </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    <div class="container my-5">
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>