Practice/4_Django/221020/articles/urls.py
from django.urls import path
from . import views


app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:article_pk>/', views.detail, name='detail'),
    path('<int:article_pk>/update/', views.update, name='update'),
    path('<int:article_pk>/delete/', views.delete, name='delete'),
    path('<int:article_pk>/comments/', views.create_comment, name='create_comment'),    # 댓글 생성
    path('<int:article_pk>/comments/<int:comment_pk>/delete/', views.delete_comment, name='delete_comment'),    # 댓글 삭제
]

Practice/4_Django/221020/articles/models.py
from django.db import models
from imagekit.models import ImageSpecField
from imagekit.processors import Thumbnail
from django.conf import settings


class Article(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=80)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    image = models.ImageField(blank=True, upload_to='images/')

    # image를 원본으로 썸네일 이미지를 만듦
    thumbnail = ImageSpecField(
        source='image',
        processors=[Thumbnail(200, 200)],
        format='JPEG',
        options={'quality': 90}
    )


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=80)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

Practice/4_Django/221020/articles/forms.py
from django.forms import ModelForm
from .models import Article, Comment


class ArticleForm(ModelForm):
    
    class Meta:
        model = Article
        fields = ['title', 'content', 'image']


class CommentForm(ModelForm):
    
    class Meta:
        model = Comment
        fields = ['content']

Practice/4_Django/221020/articles/views.py
from django.shortcuts import render, redirect
from .models import Article, Comment
from .forms import ArticleForm, CommentForm
import os
from django.contrib import messages
from django.contrib.auth.decorators import login_required


def index(request):
    articles = Article.objects.order_by('-created_at')
    
    context = {
        'articles': articles,
    }

    return render(request, 'articles/index.html', context)


@login_required
def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES)

        if form.is_valid():
            new_article = form.save(commit=False)
            new_article.user = request.user
            new_article.save()
            messages.success(request, '글 작성이 완료되었습니다.')
            return redirect('articles:detail', new_article.pk)

    else:
        form = ArticleForm()

    context = {
        'form': form,
    }

    return render(request, 'articles/create.html', context)


def detail(request, article_pk):
    article = Article.objects.get(pk=article_pk)

    comment_form = CommentForm()
    comments = article.comment_set.all()

    context = {
        'article': article,
        'comment_form': comment_form,
        'comments': comments,
    }

    return render(request, 'articles/detail.html', context)


@login_required
def update(request, article_pk):
    article = Article.objects.get(pk=article_pk)

    # 글 작성자 == 로그인한 유저
    if article.user == request.user:
        if request.method == 'POST':
            form = ArticleForm(request.POST, request.FILES, instance=article)

            if form.is_valid():
                form.save()
                messages.success(request, '글이 수정되었습니다.')
                return redirect('articles:detail', article_pk)

        else:
            form = ArticleForm(instance=article)

        context = {
            'article': article,
            'form': form,
        }

        return render(request, 'articles/update.html', context)

    # 글 작성자 != 로그인한 유저
    else:
        messages.warning(request, '작성자만 수정할 수 있습니다.')
        return redirect('articles:detail', article.pk)


@login_required
def delete(request, article_pk):
    article = Article.objects.get(pk=article_pk)

    # 글 작성자 == 로그인한 유저
    if article.user == request.user:
        # 글 지우면, 사진을 서버에서도 지우기
        if article.image:
            os.remove(article.image.path)
        if article.thumbnail:
            os.remove(article.thumbnail.path)

        article.delete()

    # 글 작성자 != 로그인한 유저
    else:
        messages.warning(request, '작성자만 삭제할 수 있습니다.')

    return redirect('articles:index')


# 댓글 생성
@login_required
def create_comment(request, article_pk):
    article = Article.objects.get(pk=article_pk)

    comment_form = CommentForm(request.POST)
    
    if comment_form.is_valid():
        new_comment = comment_form.save(commit=False)
        new_comment.article = article
        new_comment.user = request.user
        new_comment.save()

    return redirect('articles:detail', article.pk)


# 댓글 삭제
def delete_comment(request, article_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    comment.delete()

    return redirect('articles:detail', article_pk)

Practice/4_Django/221020/articles/templates/articles/create.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
  <h1 class="text-center mb-5">글 작성하기</h1>

  <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}

    <div class="text-end">
      <a class="btn btn-outline-primary" href="{% url 'articles:index' %}">목록으로</a>
      <button type="submit" class="btn btn-primary">작성하기</button>
    </div>
  </form>
{% endblock content %}

Practice/4_Django/221020/articles/templates/articles/detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load widget_tweaks %}
{% load static %}

{% block content %}
  <div class="d-flex justify-content-between align-items-center px-3 mb-2">
    <h1>{{ article.title }}</h1>
  
    <div class="d-flex">
      {% if request.user == article.user %}
      <!-- views.py에 else문이 필요한가? -->
        <form action="{% url 'articles:update' article.pk %}" class="mb-0 ms-2">
          {% csrf_token %}
          <input type="submit" value="수정" class='btn btn-primary'>
        </form>

        <form action="{% url 'articles:delete' article.pk %}" class="mb-0 ms-2">
          {% csrf_token %}
          <input type="submit" value="삭제" class='btn btn-danger'>
        </form>
      {% endif %}
    </div>
  </div>

  <div class="d-flex justify-content-between">
    <a href="{% url 'accounts:detail' article.user.pk %}" class="text-muted text-decoration-none px-3">{{ article.user }}</a>
    <p class="text-muted px-3 m-0">마지막 수정 시간: {{ article.updated_at }}</p>
  </div>
  <hr>

  <div style="min-height: 300px" class="px-3">
    {% if article.image %}
      <div class="text-center mb-4" style="height: 30rem">
        <img src="{{ article.image.url }}" alt="{{ article.image }}" class="h-100">
      </div>
    {% endif %}

    <p style="white-space: pre">{{ article.content }}</p>
  </div>
  <hr>

  <!-- 댓글 입력 -->
  <div class="px-3 my-4">
    <form action="{% url 'articles:create_comment' article.pk %}" method="POST">
      <div class="row">
        {% csrf_token %}
        
        <label for="{{ comment_form.content.label }}" class="col-1 col-form-label">
          댓글 <span class="text-primary">{{ comments|length }}</span>
        </label>

        <div class="col-11 d-flex">
          <!-- id는 어떻게 주지? -->
          {{ comment_form.content|add_class:'form-control' }}

          {% if request.user.is_authenticated %}
            <input type="submit" value="작성" class="btn btn-primary ms-3">
          {% else %}
            <input type="submit" value="작성" class="btn btn-primary disabled ms-3">
          {% endif %}
        </div>
      </div>
    </form>
  </div>

  <!-- 댓글 -->
  <div class="px-3 mb-4">
    <table class="table">
      <tbody>
        {% for comment in comments %}
          <tr style="vertical-align: middle">
            <td scope="row">{{ forloop.counter }}</td>
            <!-- 프로필 이미지 -->
            <td class="text-center">
              {% if comment.user.profile.image %}
                <img src="{{ comment.user.profile.image.url }}" class="rounded-4 border border-1" width="64px">
              {% else %}
                <img src="{% static 'images/dummy-image-square.jpg' %}" class="rounded-4 border border-1" width="64px">
              {% endif %}
            </td>
            <td class="text-center">{{ comment.user }}</td>
            <td class="text-center">{{ comment.content }}</td>
            <td class="text-end">{{ comment.updated_at|date:'Y-m-d' }}</td>
            <td class="text-end">
              {% if request.user == comment.user %}
                <form action="{% url 'articles:delete_comment' article.pk comment.pk %}" method="POST" class="m-0">
                  {% csrf_token %}
                  <input type="submit" value="삭제" class='btn btn-outline-danger'>
                </form>
              {% endif %}
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

  <div class="text-end px-3">
    <a class="btn btn-outline-primary" href="{% url 'articles:index' %}">목록으로</a>
  </div>
{% endblock %}

Practice/4_Django/221020/articles/templates/articles/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <h1 class="text-center mb-5">게시판</h1>

  <div class="text-end mb-5 px-5">
    {% if request.user.is_authenticated %}
      <a href="{% url 'articles:create' %}" class="btn btn-primary w-auto">글 작성하기</a>
    {% else %}
      <a href="" class="btn btn-primary w-auto disabled">글 작성하기</a>
    {% endif %}
  </div>

  <div class="container">
    <div class="row row-cols-sm-1 row-cols-md-2 row-cols-lg-3 g-4">
      {% for article in articles %}
        <div class="col d-flex justify-content-center">
          <a href="{% url 'articles:detail' article.pk %}" class="text-decoration-none">
            <div class="card" style="width: 18rem;">
              {% if article.thumbnail %}
                <img src="{{ article.thumbnail.url }}" class="card-img-top" alt="{{ article.thumbnail }}">
              {% else %}
                <img src="{% static 'images/dummy-image-square.jpg' %}" class="card-img-top" alt="">
              {% endif %}
      
              <div class="card-body text-dark">
                <h5 class="card-title">{{ article.title }}</h5>
                <p class="card-text card-body-text">{{ article.content }}</p>
              </div>

              <div class="card-footer text-muted">
                <p class="card-text">{{ article.user }}</p>
                <!-- <p class="card-text">{{ article.user.profile.nickname }}</p> -->
              </div>
            </div>
          </a>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock content %}

Practice/4_Django/221020/articles/templates/articles/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
  <h1 class="text-center mb-5">글 수정하기</h1>

  <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}

    <div class="text-end">
      <a class="btn btn-outline-primary" href="{% url 'articles:index' %}">목록으로</a>
      <button type="submit" class="btn btn-primary">수정하기</button>
    </div>
  </form>
{% endblock content %}