Practice/4_Django/220928-29/crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todos/', include('todos.urls')),
]

Practice/4_Django/220928-29/todos/urls.py
from django.urls import path
from . import views

app_name = 'todos'

# url namespace
# url을 이름으로 분류하는 기능
urlpatterns = [
    path('', views.index, name='index'),    # R
    path('create/', views.create, name='create'),   # C
    path('delete/<int:pk>', views.delete, name='delete'),   # D
    path('update/<int:pk>', views.update, name='update'),   # U
]

Practice/4_Django/220928-29/todos/models.py
from email.policy import default
from django.db import models

# Create your models here.
class Todo(models.Model):
    content = models.CharField(max_length=80)
    completed = models.BooleanField(default=False)
    priority = models.IntegerField(default=3)
    created_at = models.DateField(auto_now_add=True)
    deadline = models.DateField(null=True)

Practice/4_Django/220928-29/todos/views.py
from django.shortcuts import render, redirect
from .models import Todo

# Create your views here.
def index(request):
    todos = Todo.objects.all()

    context = {
        'todos': todos,
    }

    return render(request, 'todos/index.html', context)


def create(request):
    content = request.GET.get('content')
    priority = request.GET.get('priority')
    deadline = request.GET.get('deadline')

    Todo.objects.create(content=content, priority=priority, deadline=deadline)
    
    return redirect('todos:index')


def delete(request, pk):
    Todo.objects.get(id=pk).delete()
    
    return redirect('todos:index')


def update(request, pk):
    todo = Todo.objects.get(id=pk)

    todo.completed = not todo.completed
    todo.save()

    return redirect('todos:index')

Practice/4_Django/220928-29/todos/templates/todos/index.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-5" style="max-width: 500px;">
  <h2 class="text-center mb-5">To-do List</h2>
  <!-- form 작성 -->
  <div>
    <form action="{% url 'todos:create' %}">
      <div class="input-group mb-3">
        <span class="input-group-text justify-content-center" style="width: 6rem;">할 일</span>
        <input type="text" class="form-control" name="content" id="content" maxlength="80" autofocus>
      </div>
      
      <div class="input-group mb-3">
        <span class="input-group-text justify-content-center" style="width: 6rem;">우선순위</span>
        <select name="priority" class="form-select">
          <option value="1" selected>1</option>
          <option value="2">2</option>
          <option value="3">3</option>
          <option value="4">4</option>
          <option value="5">5</option>
        </select>
      </div>

      <div class="input-group mb-3">
        <span class="input-group-text justify-content-center" style="width: 6rem;">마감 기한</span>
        <input type="date" class="form-control" name="deadline" id="deadline">
      </div>

      <div class="d-flex justify-content-end">
        <input type="submit" class="btn btn-primary" value="추가">
      </div>
    </form>
  </div>
</div>

<div class="container my-5" style="max-width: 1200px;">
  <!-- Todo list -->
  <table class="table">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">우선순위</th>
        <th scope="col">할 일</th>
        <th scope="col">생성 날짜</th>
        <th scope="col">마감 기한</th>
        <th scope="col">진행 상태</th>
        <th scope="col">상태 변경</th>
        <th scope="col">삭제</th>
      </tr>
    </thead>
    <tbody>
      {% for todo in todos %}
        {% if todo.completed == True %}
          <!-- 취소선 긋기 -->
          <tr>
            <th scope="row" style="vertical-align: middle;" id="tbody-item"><s>{{ todo.id }}</s></th>
            <td style="vertical-align: middle;" id="tbody-item"><s>{{ todo.priority }}</td>
            <td style="vertical-align: middle;" id="tbody-item"><s>{{ todo.content }}</s></td>
            <td style="vertical-align: middle;" id="tbody-item date"><s>{{ todo.created_at|date:'Y-m-d' }}</s></td>
            <td style="vertical-align: middle;" id="tbody-item date"><s>{{ todo.deadline|date:'Y-m-d' }}</s></td>
            <td style="vertical-align: middle;" id="tbody-item"><s>{{ todo.completed }}</s></td>
            <td style="vertical-align: middle;"><a href="{% url 'todos:update' todo.id %}" class="btn btn-primary">변경</a></td>
            <td style="vertical-align: middle;"><a href="{% url 'todos:delete' todo.id %}" class="btn btn-danger" >삭제</a></td>
          </tr>
        {% else %}
          <tr>
            <th scope="row" style="vertical-align: middle;" id="tbody-item">{{ todo.id }}</th>
            <td style="vertical-align: middle;" id="tbody-item">{{ todo.priority }}</td>
            <td style="vertical-align: middle;" id="tbody-item">{{ todo.content }}</td>
            <td style="vertical-align: middle;" id="tbody-item date">{{ todo.created_at|date:'Y-m-d' }}</td>
            <td style="vertical-align: middle;" id="tbody-item date">{{ todo.deadline|date:'Y-m-d' }}</td>
            <td style="vertical-align: middle;" id="tbody-item">{{ todo.completed }}</td>
            <td style="vertical-align: middle;"><a href="{% url 'todos:update' todo.id %}" class="btn btn-primary">변경</a></td>
            <td style="vertical-align: middle;"><a href="{% url 'todos:delete' todo.id %}" class="btn btn-danger" >삭제</a></td>
          </tr>
        {% endif %}
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}