Project/01-Pair-04/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<int:user_pk>/', views.detail, name='detail'),
    path('<int:user_pk>/update/', views.update, name='update'),
    path('password/', views.password, name='password'),
    path('delete/', views.delete, name='delete'),
]

Project/01-Pair-04/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/update', views.update,name='update'),
    path('<int:pk>/delete/',views.delete,name='delete'),
    path('<int:review_pk>/comments/', views.create_comment, name='create_comment'),
    path('<int:review_pk>/comments/<int:comment_pk>/delete/', views.delete_comment, name='delete_comment'),
    path('search/', views.search, name='search'),
]

Project/01-Pair-04/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Project/01-Pair-04/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):

    pass

Project/01-Pair-04/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

class SignupForm(UserCreationForm):

   class Meta(UserCreationForm.Meta): 
        model = get_user_model()
        fields = ('username','email','password1','password2')
        labels = {
            'username':'닉네임',
            'email' : '이메일',
            'password1': '비밀번호',
            'password2' : '비밀번호 확인'
        }


class CustomUserChangeForm(UserChangeForm):

    class Meta(UserChangeForm):
        model = get_user_model()
        fields = ('email', 'last_name', 'first_name')
        labels = {
            'email' : '이메일',
            'last_name': '성',
            'first_name' : '이름'
        }

Project/01-Pair-04/accounts/views.py
from django.shortcuts import render,redirect
from .forms import SignupForm, CustomUserChangeForm
from django.contrib.auth.forms import AuthenticationForm ,PasswordChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import get_user_model
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required


# Create your views here.
def signup(request):
    if request.user.is_authenticated:
        return redirect('articles:index')
    
    if request.method == 'POST':
        form = SignupForm(request.POST)
        
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('articles:index')

    else:
        form = SignupForm()

    context = {
        'form' : form,
    }

    return render(request,'accounts/signup.html',context)


def login(request):
    if request.user.is_authenticated:
        return redirect('articles:index')

    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)

        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('articles:index')

    else:
        form = AuthenticationForm()

    context = {
        'form': form,
    }

    return render(request, 'accounts/login.html', context)


def logout(request):
    if not request.user.is_authenticated:
        return redirect('articles:index')

    auth_logout(request)

    return redirect('articles:index')


def detail(reqeust, user_pk):
    user = get_user_model().objects.get(pk=user_pk)
    reviews = user.review_set.all()
    comments = user.comment_set.all()

    context = {
        'user': user,
        'reviews': reviews,
        'comments': comments,
    }

    return render(reqeust, 'accounts/detail.html', context)


@login_required
def update(request, user_pk):
    user = get_user_model().objects.get(pk=user_pk)

    if request.user != user:
        return redirect('articles:index')

    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=user)

        if form.is_valid():
            form.save()
            return redirect('accounts:detail', user_pk)

    else:
        form = CustomUserChangeForm(instance=user)

    context = {
        'form': form,
    }

    return render(request, 'accounts/update.html', context)


@login_required
def password(request):
    if request.method=='POST':
        form = PasswordChangeForm(request.user, request.POST)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('accounts:detail', request.user.pk)
    
    else:
        form = PasswordChangeForm(request.user)
    
    context = {
        'form' : form,
    }
    
    return render(request, 'accounts/password.html', context)


@login_required
def delete(request):
    request.user.delete()
    auth_logout(request)

    return redirect('articles:index')

Project/01-Pair-04/accounts/templates/accounts/detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}

{% block content %}
  <h1 class="text-center my-5"><span class="text-primary">{{ user.username }}</span> 페이지</h1>

  <!-- 프로필 이미지, 닉네임, 유저네임, 소개글 -->
  <div class="container d-grid p-3 rounded-4 border border-1 mb-5">
    <div class="row row-cols-2 align-items-center">
      <div class="col-3">
          <img src="{% static 'images/dummy-image-square.jpg' %}" alt="" class="rounded-4 border border-1 w-100">
      </div>
  
      <div class="col-9 p-3" style="height: 100%">
        <div class="d-flex align-items-center justify-content-between">
          <div class="d-flex align-items-center">
            <h3 class="m-0 me-3">{{ user.username }}</h3>
            <h5 class="text-muted">{{ user.last_name }}{{ user.first_name }}</h5>
          </div>
          <div>
            {% if request.user == user %}
              <a href="{% url 'accounts:update' user.pk %}" class="btn btn-primary">회원정보 수정</a>
              <a href="{% url 'accounts:password' %}" class='btn btn-warning'>비밀번호 변경</a>
              <a href="{% url 'accounts:delete' %}" class='btn btn-danger'>회원탈퇴</a>
            {% endif %}
          </div>
        </div>
        <hr>
        <p>{{ user.email }}</p>
        <p class="m-0">intro</p>
      </div>
    </div>
  </div>

  <!-- 작성 글 목록 -->
  <div class="accordion mb-4" id="accordionReview">
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingOne">
        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseReview" aria-expanded="true" aria-controls="collapseOne">
          글 목록
        </button>
      </h2>
      <div id="collapseReview" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionReview">
        <div class="accordion-body">
          {% for review in reviews %}
            <a href="{% url 'articles:detail' review.pk %}" class="text-dark text-decoration-none">
              <div class="px-3">
                <p class="text-muted m-0 text-decoration-none me-3">{{ review.user }}</p>
              
                <div class="d-flex justify-content-between align-items-center">
                  <p class="text-muted m-0 text-decoration-none me-3">{{ review.title }}</p>

                  <div class="d-flex align-items-center">
                    <p class="m-0 me-3">{{ review.created_at|date:'Y-m-d' }}</p>
                    
                    {% if review.user == request.user %}
                    <form action="{% url 'articles:delete' review.pk %}" method="POST" class="m-0">
                      {% csrf_token %}
                      <input type="submit" value="삭제" class="btn btn-danger me-3">
                    </form>
                    {% endif %}
                  </div>
                </div>
              </a>
              <hr>
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>

  <!-- 작성 댓글 목록 -->
  <div class="accordion" id="accordionComment">
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingOne">
        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseComment" aria-expanded="true" aria-controls="collapseOne">
          댓글 목록
        </button>
      </h2>
      <div id="collapseComment" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionComment">
        <div class="accordion-body">
          {% for comment in comments %}
            <a href="{% url 'articles:detail' comment.review.pk %}" class="text-dark text-decoration-none">
              <div class="px-3">
                <div class="d-flex justify-content-between align-items-center mb-2">
                  <p class="text-muted m-0 text-decoration-none me-3">{{ comment.user }}</p>
                  <p class="text-muted m-0 text-decoration-none me-3">{{ comment.review.title }}</p>
                </div>
              
                <div class="d-flex justify-content-between align-items-center">
                  <p class="m-0">{{ comment.content }}</p>
                  
                  <div class="d-flex align-items-center">
                    <p class="m-0 me-3">{{ comment.created_at|date:'Y-m-d' }}</p>
                    
                    {% if comment.user == request.user %}
                    <form action="{% url 'articles:delete_comment' comment.review.pk comment.pk %}" method="POST" class="m-0">
                      {% csrf_token %}
                      <input type="submit" value="삭제" class="btn btn-danger me-3">
                    </form>
                    {% endif %}
                  </div>
                </div>
              </a>
              <hr>
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
{% endblock  %}

Project/01-Pair-04/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
  <h1 class="text-center my-5">로그인</h1>

  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}

    <div class="text-end">
      <input type='submit' class='btn btn-primary' value='로그인'>
    </div>
  </form> 
{% endblock %}

Project/01-Pair-04/accounts/templates/accounts/password.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
  <h1 class="text-center my-5">비밀번호 변경</h1>

  <form action="{% url 'accounts:password' %}" method='POST'>
    {% csrf_token %}
    {% bootstrap_form form %}

    <div class="text-end">
      <input type="submit" value="수정하기" class="btn btn-primary">
    </div>
  </form>
{% endblock %}

Project/01-Pair-04/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
  <h1 class="text-center my-5">회원가입</h1>

  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}

    <div class="text-end">
      <input type='submit' class='btn btn-primary' value='회원가입'>
    </div>
  </form> 
{% endblock %}

Project/01-Pair-04/accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
	<h1 class="text-center my-5">회원정보 수정</h1>

	<form action="" method="POST">
		{% csrf_token %}
		{% bootstrap_form form %}

		<div class="text-end">
			<!-- <input type="sumbit" class="btn btn-primary" value="수정하기"> -->
			{% bootstrap_button content="수정하기" button_type="submit" button_class="btn-primary" %}
		</div>
	</form> 
{% endblock %}